# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Popup.create([{name: "BYOB Summer Brunch ", address: "945 Valencia St, San Francisco, CA ", description: "family-style brunch in a private mansion", price: "$$$", hours: "11:30am - 2:00pm", image: "http://i.imgur.com/mJCJ5Ep.jpg", day: "Sunday, Aug 3rd", website: "http://www.nakedkitchensf.com/", category: "Food" }])
Popup.create([{name: "Loqui", address: "3605 18th St, San Francisco, CA ", description: "Mexican Antojitos", price: "$", hours: "7:30pm - 12:00am", image: "http://i.imgur.com/KkaqafJ.jpg", day: "Friday-Saturday", website: "http://www.eatloqui.com/", category: "Food" }])
Popup.create([{name: "Tango & Stache", address: "3153 17th St, San Francisco, CA ", description: "Pork Belly Tacos ", price: "$", hours: "11:00am - 6:00pm", image: "http://i.imgur.com/sHSIgme.jpg", day: "Friday", website: "http://www.tangoandstache.com/", category: "Food" }])
Popup.create([{name: "Trilogi SF", address: "3066 24th st, San Francisco, CA ", description: "thai tapas", price: "$$", hours: "6pm - 10pm", image: "http://brandoracollective.com/wp-content/uploads/2014/04/TrilogiSF-4001.jpg", day: "Tuesdays", website: "https://www.trilogisf.com", category: "Food" }])
Popup.create([{name: "Hapa Ramen", address: "422 haight st, San Francisco, CA ", description: "quirky ramen & tacos", price: "$", hours: "6:00pm - 10:00 pm", image: "http://www.schmoozd.com/wp-content/uploads/Hapa-Ramen.jpg", day: "Mondays", website: "https://www.haparamensf.com", category: "Food" }])
Popup.create([{name: "Belly Burgers", address: "2 Marina Blvd, San Francisco, CA ", description: "Pork Belly burgers with a Vietnamese twist", price: "$", hours: "5:00pm - 10:00pm", image: "http://i.imgur.com/Ht8kpP7.jpg", day: "Friday", website: "http://bctbellyburgers.com/", category: "Food" }])
Popup.create([{name: "Chaparral", address: "471 Haight St, San Francisco, CA ", description: "high end pop-up restaurant with a BYOB policy", price: "$$", hours: "6:00pm - 11:00pm", image: "http://i.imgur.com/gHC0Ajx.jpg", day: "Thursday - Saturday", website: "http://www.chaparralsf.com/home.html", category: "Food" }])
Popup.create([{name: "Fused", address: "901 Larkin St, San Francisco, CA ", description: "Mexican and Asian-fusion dishes", price: "$", hours: "7:00am - 10:30am", image: "http://i.imgur.com/EmmQxD7.jpg", day: "Saturday - Sunday", website: "http://houseofthaisf.com/", category: "Food" }])
Popup.create([{name: "Wesburger", address: "639A divisadero st, San Francisco, CA ", description: "burger popup", price: "$$", hours: "6:00 pm - 10:00 pm", image: "http://i.imgur.com/8UckhHt.jpg", day: "Wednesdays", website: "https://www.facebook.com/thewesburger", category: "Food" }])
Popup.create([{name: "Bespoke Doughnuts", address: "2344 market st, San Francisco, CA ", description: "doughnut popup", price: "$", hours: "8:30 am - 6:00 pm", image: "http://assets3.thrillist.com/v1/image/1189652/size/tl-horizontal_main", day: "Monday-Saturday", website: "https://www.facebook.com/bespokedoughnuts", category: "Food" }])
Popup.create([{name: "Six-Course Autumn Bounty Dinner", address: "Naked Kitchen, 945 Valencia St, San Francisco, CA ", description: "Savor the hearty, earthy flavors of fall as imagined by pop-up partners Eddie Lau and Luis Villavelasquez.", price: "$$$", hours: "6:00 pm", image: "http://i.imgur.com/7qiUZwm.jpg", day: "Sat, Oct. 18th", website: "http://www.nakedkitchensf.com/", category: "Food" }])
Popup.create([{name: "Late Night Korean Bites", address: "Hog & Rocks, 3431 19th St, San Francisco, CA ", description: "Namul, seasonal marinated vegetables scented with sesame oil, and spicy kimchi", price: "$$$", hours: "10:00pm - 1:00am", image: "http://i.imgur.com/7qiUZwm.jpg", day: "Thursday", website: "http://www.hogandrocks.com/", category: "Food" }])
Popup.create([{name: "Malyasian Dinner", address: "Naked Kitchen, 945 Valencia St, San Francisco, CA", description: "tasting menu highlighting the flavors and ingredients of Malaysia", price: "$$$", hours: "6:00pm - 9:00pm", image: "http://i.imgur.com/7qiUZwm.jpg", day: "Sat, Oct. 25th", website: "http://www.nakedkitchensf.com/", category: "Food" }])
Popup.create([{name: "The Lunch Pad", address: "Noir Lounge, 581 Hayes St, San Francisco, CA", description: "artisan sandwiches", price: "$$", hours: "8:00am - 2:30pm", image: "http://i.imgur.com/5r58jkc.jpg", day: "Monday - Friday", website: "http://thelunchpadsf.com/", category: "Food" }])
Popup.create([{name: "Sorrel Pop-Up Restaurant", address: "The Hotel Rex, 562 Sutter Street, San Francisco, CA", description: "Italian-influenced Four Course Tasting Menu ", price: "$$", hours: "8:00am - 2:30pm", image: "http://i.imgur.com/5r58jkc.jpg", day: "Thursday", website: "http://thelunchpadsf.com/", category: "Food" }])